name: Deploy Firebase Security Rules
on:
  workflow_dispatch:
  push:
    paths:
      - firebase/**
    branches:
      - develop
      - main

jobs:
  apply-security-rules:
    name: Deploy Firebase Rules 
    runs-on: ubuntu-latest
    environment: FIREBAE
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy prod
        uses: w9jds/firebase-action@master
        with:
          args: deploy --force --only firestore
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
          PROJECT_PATH: ./firebase
        if: github.ref_name == 'main'
