name: Deploy Firebase Security Rules
on:
  push:
    paths:
      - firebase/**
    branches:
      - develop
      - main

jobs:
  apply-security-rules:
    name: Deploy Firebase Rules 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy dev
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: fir-rule-c8168
          PROJECT_PATH: ./firebase
        if: github.ref == 'refs/heads/development'

      - name: Deploy prod
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: fir-rule-c8168
          PROJECT_PATH: ./firebase
        if: github.ref == 'refs/heads/main'
