name: DEV - Apply Firebase Security Rules
on:
  - workflow_dispatch
  - pull_request

jobs:
  apply-security-rules:
    name: Apply Firebase Rules (Development)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Apply
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ env.FIREBASE_PROJECT_ID }}
          PROJECT_PATH: ./firebase