name: Deploy Firebase Security Rules
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  apply-security-rules:
    name: Deploy Firebase Rules 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Diff Firestore Rules
        id: diff_firestore_rules
        uses: technote-space/get-diff-action@v5
        with:
          PATTERNS: |
            firestore.rules

      - name: echo
        run: echo ${{ steps.diff_firestore_rules.outputs.diff }}
        run: echo ${{ env.GIT_DIFF }}

      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: fir-rule-c8168
          PROJECT_PATH: ./firebase
        if: steps.diff_firestore_rules.outputs.diff