name: Deploy Firebase Security Rules
on:
  - workflow_dispatch
  - pull_request

jobs:
  apply-security-rules:
    name: Deploy Firebase Rules 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - run: |
            echo ${{ env.FIREBASE_PROJECT_ID }}
            echo ${{ secrets.FIREBASE_TOKEN }}
      - name: deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: fir-rule-c8168
          PROJECT_PATH: ./firebase